### ISSUE TITLE
loadMore clears results

### ISSUE THREAD

**Issue by Skulmuk** [matteodem/meteor-easy-search#374]
We have it set up that when a specific button is rendered, the loadMore method is called. This button sits at the bottom of the list of search results. In older versions, this worked fine, but in the new version it seems to interfere with the window scroll - instead of just loading more results, the window appears to clear the list of results and re-render them all (plus the extra ones requested), which scrolls the window back to the top of the list.

Apologies if that's unclear - a bit short on time to explain more fully.

**Comment by matteodem** [comment]
Yes, right now it does not just add the new documents in a separate subscription, which explains this behaviour. I'll have a look at this as soon as the other more requested features are implemented. It's going to be a bit tricky though.

For now there's always the possibility of using some css / javascript before loading the documents.

**Comment by Skulmuk** [comment]
Thanks for the reply, we're happy to stay back on the older version for now, so no rush! :)

**Comment by ignacy130** [comment]
@Skulmuk which version are you using? So I could avoid behavior you described as I don't like it as well :)

**Comment by vivekdtiwari** [comment]
I have the same issue. Can someone please mention which is the old working version? Thanx

**Comment by raisudeen** [comment]
@Skulmuk @matteodem Can you please let me know the version to avoid this issue? Also, it would be better if you share the example code to implement it with that particular older version.

**Comment by matteodem** [comment]
I'm rather busy right now with work right now. You'd probably need to switch down to 1.*, but I recommend having some css/js logic for now that keeps the height the same when loading new docs.

**Comment by raisudeen** [comment]
@matteodem Sorry. I will try my level best. Between, fix it when you are free. Thanks a lot for your reply.

**Comment by Skulmuk** [comment]
Sincere apologies for the late reply, gents - we've been busy with other things and this issue has slipped down the pile....

We've switched recently from 2.0.0 to 2.0.8 (we stayed at version 2.0.0 to circumvent this issue) as part of our upgrade to Meteor's RC4 release for 1.3. I've forked the code and had a poke around. From what I can gather, [this function](https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/core/search-collection.js#L61) is called twice when loadMore() is called - you can see it by adding `console.log(mongoCursor.count())` before it returns. 

The first call returns an empty Mongo cursor (which throws the UI back to the top of the list, I assume because it's now considered to be an empty list of search results) and the second then returns and populates with the relevant data, which makes it appear as if the loadMore is at fault. However, I think it's the underlying find() function and surrounding code that's at fault. 

Out of interest, I tried to fix it by forcing [this line](https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/each/each.js#L25) to check the cursor's publication ready state before returning. This removed the duplicated call described above, but didn't fix anything else.

@matteodem I hope my digging was of some use and was able to shed some light on what's going on.

**Comment by matteodem** [comment]
Thank you for having a closer look at this! Will invest some time again this friday. Would be cool to get it done as it's disturbing to quite a lot of users of this library.

**Comment by jamiecollinson** [comment]
@matteodem - thanks for looking at this, causing issues for me as well, and so I've just - reluctantly - switched to pagination until the issue is resolved.

If there's anything I can do to help with the issue let me know. Aside from anything it's really interesting to see how easysearch is put together :-)

**Comment by raisudeen** [comment]
@matteodem Tons of thanks for looking in to it. Eagerly waiting for your update. :+1:

**Comment by matteodem** [comment]
This is fixed as of last version `2.0.9`

**Comment by raisudeen** [comment]
@matteodem Thanks alot for fix. It is working fine now. You made my day. :)

**Comment by Skulmuk** [comment]
Thanks, @matteodem - I'll get it incorporated as soon as I can!

**Comment by steven-tib** [comment]
Hi @matteodem, it seems that in the version 2.1.4 this bug is back, or should I change any settings to avoid reloading all results on "loadmore" ? 
I've downgraded to 2.0.9 and it works fine again (not reloading all, but just the additionnal results) so I'll stay with this one for now. 
I guess you're pretty busy but hope you can find some time to have a look at it. Thanks in advance

**Comment by matteodem** [comment]
is the bug still there with the latest version?

**Comment by steven-tib** [comment]
@matteodem sorry for the late reply, the bug is gone, I'm using version 2.1.6 
thanks a lot for the fix
